### ISSUE TITLE
Submodules got invisible

### ISSUE THREAD

**Issue by antis81** [macgitver/MacGitver_oldie#10]
@scunz The last time I compiled MGV I noticed, the submodules are not shown anymore in the repo tree. Think this is due to the changes in event handling. Are you working on that or should I fix this?

**Comment by scunz** [comment]
@antis81, Uh? Sorry, wasn't aware of that problem. However, I cannot reproduce with current code. Can you check if this still is the case?

It was actually much more difficult to get rid of the compat Repository-Changing code. So there were lots of changes I didn't even expect...

**Comment by antis81** [comment]
Doh, my fault. I tried with a broken repo with missing files in submodule folder. Seems all good so far.

**Comment by scunz** [comment]
Maybe I should have taken those changes and submit PRs for them. It's just that sometimes it feels so silly having all the submodules ready to "commit" but instead setup 3 PRs, look at them again and commit from web...

**Comment by antis81** [comment]
> It's just that sometimes it feels so silly having all the submodules ready to "commit" but instead setup 3 PRs, look at them again and commit from web...

Maybe this is because our world always seems to be fast. We need to learn patience again, doing the needed steps to get a satisfying result. Over and over again. Even if changes seem small. In todays "task driven development" thinking, PR's are a good way to bring in features or changes one by one instead of all together, having to resolve lots of conflicts, not knowing what the changes relate to. Like discussed before, the real problem lies in spreading a feature branch over several submodules. This actually makes it so sloooow :athletic_shoe:. The only way I know is to setup a branch with the same name on all modules plus the super repo from a common starting point and integrate them later one by one. Super repo last. This workflow can break in very few cases, when not all modules can be merged immediately due to bigger conflicts. But even then it is unlikely to really break the project. If we manage to get some workflow supporting mechanism into MGV, it could become one of the coolest GUI's out there. But as you already said -> This is another issue(s) :smile:.
