### ISSUE TITLE
Main Goals for V0.1

### ISSUE THREAD

**Issue by antis81** [macgitver/MacGitver_oldie#4]
# Git repo visualization (readonly):
- [x] Show the complete repository's structure and history
- [x] Show the repositories working directory
- [x] Show the differences of a commit (library: libDiffView)
- [x] Show the current repo's index (stage area) macgitver/libGitWrap#10 macgitver/MacGitverModules#57
# Git local functionality:
- [x] edit current repo's index
- [ ] commit to current branch
# Git remote functionality:
- [ ] fetch
- [ ] push
- [x] clone
# Visualization library libHeaven:
- [x] basic concept for view / layout system macgitver/libHeaven#11 macgitver/MacGitverModules#54 macgitver/libMacGitverCore#1
# Manage application settings:
- [x] basic generator for readable configurations (namely CfgComp)
# Information management / Documentation:
- [x] setting up basic locations for wiki and project home page
- [x] autogenerating developer documentation
- [ ] publish api docs
- [x] setup a webpage generator
# Deployment:
- [ ] linux packages ( apt (maybe others as well as rpm, deb, ...) )
- [ ] win32 installer ( InnoSetup or anything like that )
- [ ] mac packages ( dmg, (homebrew would be even cooler) )

**Comment by scunz** [comment]
Why did you close this one?

**Comment by antis81** [comment]
Sorry, I just did try something out:
It is actually an exact copy now of the milestone. Do you think it we should reopen and leave milestone empty instead?

**Comment by scunz** [comment]
Wait a second :-)

**Comment by scunz** [comment]
hmm, the milestone view doesn't list the `x of y tasks done'` like issue search does. However, it is easier to track those things in issues than in milestones (you can directly click on the check box and mark things as done etc.)

**Comment by scunz** [comment]
Ah, now i see: This works only with PRs :-)

**Comment by antis81** [comment]
Ok, so we leave it like that: Makes things more easy. Removing the milestone description instead and just link to this issue.

**Comment by scunz** [comment]
The issue is already assigned to the milestone. However, the idea of such collective issues contradicts a bit with the categorizing, you mentioned in issue 1.

Let's do it like that:
- Discuss & collect everything that has to be done for v0.1 in _this_ issue.
- When we're done with that: create individual issues for the topics that need to be done, then assign those to the milestone.

This way, we'll get a progress bar on the milestone and we're actually able to close bugs from within PRs in the other submodules.

**Comment by antis81** [comment]
Sounds totally good. Thus, we have the overview here and everything else at the appropriate places. Some subproject management on GH would be cooler though, but until then ... this is a good workaround.

**Comment by scunz** [comment]
I'm not sure what you mean by submodule management. But the more I dig into submodules, the more inconvenient GH becomes. Maybe you're looking for some linking like i've done for the uncrappify branches in the description of this issue.

**Comment by scunz** [comment]
![assignment](https://f.cloud.github.com/assets/1700771/243422/210a6420-8a46-11e2-8b79-0542dbb47c19.png)
Funny...
1. I did that assignment.
2. It shows the complete-ness of this issue while at the same time in the milestone-view it doesn't.

**Comment by scunz** [comment]
For deployment, see my thoughts at #5.

**Comment by antis81** [comment]
Btw. @jakro00, @scalm and @claus007: Would you like to join the show?

**Comment by antis81** [comment]
@scunz After the (not so spectacular :) eclipse is over now .... I just looked at this issue from the earlier days of MGV and found, the focus is set plain to the wrong things! It is a feature-based view, which really makes no sense in MacGitver. I.e. this is the least thing we need to focus on, because the features are defined by the underlying concepts. Well, back then I didn't see it, but now I do. I changed my very tight viewpoint right now!

The fortunate thing is:
We already have a much better, real roadmap in redmine (might not be complete, but a very useful foundation) -> [see here](https://redmine.macgitver.org/projects/macgitver/wiki/Roadmap).

I'll close this issue short and painless to remove confusion (and the still existing divergence of the basic concepts). It will be much easier to rewrite topics in the context of the right concept in redmine, than trying to integrate this issue. So: Simply forget about this, please. :put_litter_in_its_place:
