### ISSUE TITLE
Removal of Submodules

### ISSUE THREAD

**Issue by scunz** [macgitver/MacGitver_oldie#8]
@antis81 Can I remove the ModSubmodule code?

**Comment by antis81** [comment]
Yeah, feel free to remove. We talked about keeping that some time ago :clock1:. But actually most of the former structure was moved into the repo tree. What's left are some unfinished add/remove dialogs from the beginning, but sure we find better ways to achieve that :smile:.

**Comment by scunz** [comment]
Add/Remove? Is this code working? Should I move it somewhere?

I could as well just disable the `ADD_SUBDIRECTORY` call in the parent CMakeLists file. The reasoning behind is that i want to get rid of the old repo-changed code - and modSM is one of the few remaining consumers of that.

**Comment by antis81** [comment]
Yes, that's an idea. Without looking into the code I'd say we don't need that anymore. It is currently not used anywhere in MGV where it would make sense. We tried out some nice ideas there though and I'd like to keep them in mind. So removing the entry from CMakeLists.txt is a good deal until we decide how to proceed further.

**Comment by scunz** [comment]
Also, long done ^^
